# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/longhorn.io/recurringjob_v1beta2.json
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: critical-snapshot-hourly
  namespace: {{ .Release.Namespace }}
spec:
  concurrency: 2
  cron: "0 * * * *"          # hourly at :00
  groups: ["critical"]
  retain: 24
  task: snapshot
  labels:
    job: critical-snapshot-hourly

---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: critical-backup-daily
  namespace: {{ .Release.Namespace }}
spec:
  concurrency: 1
  cron: "30 2 * * *"         # 02:30 daily
  groups: ["critical"]
  retain: 30
  task: backup
  labels:
    job: critical-backup-daily
