apiVersion: v2
name: cert-system
version: 0.0.8
dependencies:
  - name: cert-manager
    version: v1.19.3
    repository: https://charts.jetstack.io
  - name: trust-manager
    version: v0.20.3
    repository: https://charts.jetstack.io
  - name: step-certificates
    version: "1.29.0"
    repository: https://smallstep.github.io/helm-charts
  - name: step-issuer
    version: "1.9.11"
    repository: https://smallstep.github.io/helm-charts
