apiVersion: v2
name: spoolman
description: Keep track of your inventory of 3D-printer filament spools.
type: application
version: 0.1.5
appVersion: "0.22.1"
dependencies:
  - name: app-template
    version: 4.5.0
    repository: https://bjw-s-labs.github.io/helm-charts
