{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kured-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kured-webhook
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kured-webhook
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
{{- end }}
