{{- if .Values.webhook.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kured-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kured-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kured-webhook-longhorn
  labels:
    app.kubernetes.io/name: kured-webhook
rules:
  - apiGroups:
      - longhorn.io
    resources:
      - nodes
    verbs:
      - get
      - list
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kured-webhook-longhorn
  labels:
    app.kubernetes.io/name: kured-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kured-webhook-longhorn
subjects:
  - kind: ServiceAccount
    name: kured-webhook
    namespace: {{ .Release.Namespace }}
{{- end }}
