{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kured-webhook
  namespace: {{ .Release.Namespace }}
data:
  server.py: |-
    {{- .Files.Get "files/kured-webhook/server.py" | nindent 4 }}
{{- end }}
