apiVersion: v2
name: victoria-metrics
description: VictoriaMetrics long-term storage for Prometheus metrics
type: application
version: 0.1.2
appVersion: 1.135.0
dependencies:
  - name: victoria-metrics-single
    version: 0.31.0
    repository: https://victoriametrics.github.io/helm-charts/
