apiVersion: v2
name: victoria-metrics
description: VictoriaMetrics long-term storage for Prometheus metrics
type: application
version: 0.0.1
appVersion: 1.106.1
dependencies:
  - name: victoria-metrics-single
    version: 0.15.9
    repository: https://victoriametrics.github.io/helm-charts/
