apiVersion: v2
name: longhorn
description: Distributed block storage
version: 0.1.5
appVersion: 1.11.0

dependencies:
  - name: longhorn
    version: 1.11.0
    repository: https://charts.longhorn.io
