apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    - post-delete-finalizer.argocd.argoproj.io
    - post-delete-finalizer.argocd.argoproj.io/cleanup
  name: node-feature-discovery
  namespace: argocd
  ownerReferences:
    - apiVersion: argoproj.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: ApplicationSet
      name: root
      uid: 0c3323b9-2b93-43c0-8a93-3f6273d5876b
spec:
  destination:
    name: in-cluster
    namespace: node-feature-discovery
  ignoreDifferences:
    - jsonPointers:
        - /spec/volumeName
        - /spec/storageClassName
      kind: PersistentVolumeClaim
    - jsonPointers:
        - /data
      kind: Secret
      name: lldap-authelia-bind-user
      namespace: auth-system
    - jsonPointers:
        - /data
      kind: Secret
      name: authelia-secrets
      namespace: auth-system
    - jsonPointers:
        - /data
      kind: Secret
      name: gitea-admin-secret
      namespace: gitea
    - jsonPointers:
        - /data
      kind: Secret
      name: monitoring-system-grafana
      namespace: monitoring-system
    - jsonPointers:
        - /data
      kind: Secret
      name: alertmanager-monitoring-system-kube-pro
      namespace: monitoring-system
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
  project: default
  source:
    path: k8s/foundation/node-feature-discovery
    repoURL: http://gitea-http.gitea:3000/ops/k8s-homelab
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    retry:
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 16m
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
