apiVersion: v2
name: argocd
version: 0.0.21
dependencies:
  - name: argo-cd
    version: 9.3.4
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-apps
    version: 2.0.4
    repository: https://argoproj.github.io/argo-helm
