apiVersion: v2
name: argocd
version: 0.0.22
dependencies:
  - name: argo-cd
    version: 9.4.0
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-apps
    version: 2.0.4
    repository: https://argoproj.github.io/argo-helm
  - name: argo-events
    version: 2.4.19
    repository: https://argoproj.github.io/argo-helm
