apiVersion: v2
name: authelia
version: 0.0.12
dependencies:
  - name: authelia
    version: 0.10.49
    repository: https://charts.authelia.com
  - name: app-template
    version: 4.6.0
    repository: https://bjw-s-labs.github.io/helm-charts
