apiVersion: v1
kind: ConfigMap
metadata:
  name: discord-bot-code
data:
  pyproject.toml: |
{{ .Files.Get "files/discord-bot/pyproject.toml" | indent 4 }}
  server.py: |
{{ .Files.Get "files/discord-bot/server.py" | indent 4 }}
