apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: terrariapublic
spec:
  entryPoints:
    - terrariapublic
  routes:
    - match: HostSNI(`*`)
      services:
        - name: terraria
          port: 7777
