# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls-certificate
  # Traefik runs in kube-system and needs the secret in its namespace
  namespace: kube-system
spec:
  secretName: wildcard-tls-certificate
  dnsNames:
    - "*.msng.to"
    - "msng.to"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
