apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: kyverno
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: kyverno
  ignoreDifferences:
    - jsonPointers:
        - /spec/volumeName
        - /spec/storageClassName
      kind: PersistentVolumeClaim
    - jsonPointers:
        - /data
      kind: Secret
      name: monitoring-system-grafana
      namespace: monitoring-system
    - jsonPointers:
        - /data
      kind: Secret
      name: alertmanager-monitoring-system-kube-pro
      namespace: monitoring-system
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
  project: default
  source:
    path: k8s/foundation/kyverno
    repoURL: http://gitea-http.gitea:3000/ops/k8s-homelab
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    retry:
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 16m
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - ClientSideApplyMigration=false
