apiVersion: v2
name: kyverno
description: Kubernetes Native Policy Management
version: 0.0.11
appVersion: "v1.17.0"

dependencies:
  - name: kyverno
    version: 3.7.0
    repository: https://kyverno.github.io/kyverno
