apiVersion: v2
name: kyverno
description: Kubernetes Native Policy Management
version: 0.0.10
appVersion: "v1.16.2"

dependencies:
  - name: kyverno
    version: 3.6.2
    repository: https://kyverno.github.io/kyverno
