apiVersion: v2
name: kyverno
description: Kubernetes Native Policy Management
version: 0.0.12
appVersion: "v1.17.1"

dependencies:
  - name: kyverno
    version: 3.7.1
    repository: https://kyverno.github.io/kyverno
