apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: crowdsec
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: crowdsec
  ignoreDifferences:
    - jsonPointers:
        - /spec/volumeName
        - /spec/storageClassName
      kind: PersistentVolumeClaim
    # Bouncer key is managed manually after initial deploy
    - jsonPointers:
        - /data
        - /stringData
      kind: Secret
      name: crowdsec-bouncer-key
      namespace: crowdsec
    # crowdsec-secrets is a generated secret
    - jsonPointers:
        - /data
        - /stringData
      kind: Secret
      name: crowdsec-secrets
      namespace: crowdsec
    # Middleware changes made by bootstrap job
    - group: traefik.io
      jqPathExpressions:
        - .spec.plugin."crowdsec-bouncer".CrowdsecLapiKey
      kind: Middleware
      name: crowdsec-bouncer
      namespace: crowdsec
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
  project: default
  source:
    path: k8s/platform/crowdsec
    repoURL: http://gitea-http.gitea:3000/ops/k8s-homelab
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      # selfHeal: false
    retry:
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 16m
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
