apiVersion: v2
name: homepage
description: Homepage dashboard
type: application
version: 0.1.0
appVersion: "v1.8.0"
dependencies:
  - name: homepage
    version: 4.5.0
    repository: oci://ghcr.io/m0nsterrr/helm-charts
