apiVersion: ENC[AES256_GCM,data:HyI=,iv:0tNfCiZW6r262hBwOMs5s8QOliAoceoVU7fxMP3F8EQ=,tag:0n+19yA+eME8spaRF8Ov6Q==,type:str]
clusters:
    - cluster:
        certificate-authority-data: ENC[AES256_GCM,data:bTiCqgWr5w9lKL/K6Bi8lnksDt7ERGlHEZCD05q7VZoKhwnrm6qL6Zj50DNDjrXIFgYV7KljYe9eXT3iLtyjT8CrvTjrHnIlECvbrE/XnjIx/EU4F7w+y2ZbzsurMCu5yrKYhQoMVRNLcAYqhIrC6rCla8EpnhzIpWox26ze+I8o0ubThJRPBeWzN5SV8uvpMh7IwkUl/vPSzdBfGQlpQjxyuc7wHhO7KWOmMVC2HXulYT5WdxclViK9gTSc2qsKCLC3QOv2pa4MFPhJjIAQU5KUODmuUTMDaqi0FyuSqFpiK3NqRIL4KVFUumPxkZYqb8xImQk3wbGXi7cQXU+FqPif1cCdWK+mAXYS5cWPxNODnaTcUN5y0rQqV8eK/jdYXRYUB3ndPqrTQnPVbha5BhpYLnez2RhaTs/ayvd7NYfdCcaxSsSvxMVR7Mq4cdoBy/yOiSr9hnYibQxHjQ5ghOTuy2sz9I6eV5BPSMDveSxKBnqqe9/N4D7uybe66N4MP3fuk4MYmHVLCRk5cL5z2XouC84O+DDP4YC0Rvqh+v+7w5XkM280gwSy/BvzoVh77wfxWaiOaT7E6cYGSb9St+ujePLfMAPoqIHQZSFJZ0jP/1WnuXbKfjNs5GNV7Ab7XlZ4IVtcIirlzLwO4LI62XOSZVde5RefKFFodRjz7nq8yiP1iUoly0uUVK+bmarXFVNbW0YI1tsiio/00vSJHtBmGXuo7tBpxyOOhc4N36F49ZKBJIXrGXfb5EdF3Tg0AXnC27gFE/VxVCaJaumq1XsZ9qr5F8Cu2L8FjcRb8UfJDKeUe2cHONGmeof6e3gjDaFql5reOX0sgAB6YdE7ICRj7PBch4Io5DDbbgTmb74FtiIeLdpFRdiJqjZ+aRiAC7VJ/9MerLuTiEW5ZodaaesUkPnBBAlMyQfhDi5lvtDxfL7YHis5pbAHMthLdGKgnLNsyc8nr5fQXy9NzDl6+/AFF6E3N9NUBmeylUfEHXRnyVggoZmQgg==,iv:TKaboxVOpg3HNo3Wpau2VbmEyBNEGoC7bUpZmedPWl4=,tag:r16aHC0/8BR01o4rY0pgYg==,type:str]
        server: ENC[AES256_GCM,data:dLOH6kpNjShWYZbYVHVWrdhNp9FiAZX8,iv:WuujOAkFWol6yoLMo2VppDz9taGyVmVWWgZiyLxseWg=,tag:SuFeSvWnSnuZMCWwZU6gEQ==,type:str]
      name: ENC[AES256_GCM,data:HbO62szaDw==,iv:e/YAVNUYpTTioYtHeBDgz0Whtk9+dXeVnmb4WUs2SVU=,tag:ihxEzgRIiC4DDKWUlzWypg==,type:str]
contexts:
    - context:
        cluster: ENC[AES256_GCM,data:ITdNLmy82Q==,iv:/bvHbjDuuhTf1WoRQLEZ4kGUYXkIYpCYAH+RySx75Ak=,tag:mOtC2fIiN6v9g6hNAng3RQ==,type:str]
        user: ENC[AES256_GCM,data:MPjRVaB1MQ==,iv:DmrlJNyCIDmc7FZy0cmWTlVUsRxW+cfcYN9NMcMMPIk=,tag:Tqt/3iyj1qg89SQX6WjhLQ==,type:str]
      name: ENC[AES256_GCM,data:W3AAtPeUrQ==,iv:TLCbknp35qU4w1VQPXpwXMY4syR/S6WoFX0KSWpe2N0=,tag:y/+HXccM6L/msZSGnfrHsw==,type:str]
current-context: ENC[AES256_GCM,data:B9Lgs3yFnw==,iv:1wieHfJ16whzqzE4uT20vk+TbJzzZd47xnnNqZqis6k=,tag:9ZDck7BPwKVcIwcvR+Ezow==,type:str]
kind: ENC[AES256_GCM,data:Cz7r3USi,iv:r3CpECQqGzE5YA+tyxtK5gbIAk+IUOd8rnEFxUcdZRs=,tag:+PHNYtgwQ4JT0g3VR7GIKQ==,type:str]
users:
    - name: ENC[AES256_GCM,data:to/IL2ghAw==,iv:X8jnrl4N+y5LIK/5IhLWuyb2wlL1P884oXNgnLbVkQQ=,tag:obRUZeH2Dx0u7co5wV+eww==,type:str]
      user:
        client-certificate-data: ENC[AES256_GCM,data:RyommpBzms4RN1piKvyqMniz8NB9GUcxmXZTG6VGuj9lyc8LvZE/2/yHh6lMcstqrdK7MIrY0/sQ22e+HNxpSgG9HMTF7vxfU8icClmHuHJOpt4NhQI6InZPqIU4wZvAYXfgbca92A34+PI6/f9+CYeQwm+yF9oPT/G9SrU+1aFziOBImF37P+GPztCibrGWit3MyAdOwwnlP+fc5F0fpTG1Ynbdg+oDKCL4+6PuFFcWRurAwbpfL3LydHK0z+TJADeBElVEMOuzlaNNU2UC59fFWoIOU3VMN7ZRb6Yya4l9KZkj7m090+ViJGcbTYmDZQQy48xddhU4uEdC1yKcztCZBuX5SLQx7P+TLhMMheVmulqUsrHEDDVpjTgDGOK7HKDPlITWgJf+SZsmHLDhEG7vK21gwoB+xlBrt12qVwEKd5cQ4JYkWWnYHsNg5OBDkGiCiHVuhY2iOB38oIWaNX2gcmn6Z2PxcxEZIowW7EfUxpMRMh+NgoRAPD9PIWir8KVdAdBvN9xg948YrGMBm9c6oxoJgc3txeIOJXkvi98m5YyGI9ag54uWos0CDlnOxF6p6p4ISyUreqx7Sfzyw0WrhPFZ5FlTl2S/9Nhsm2NluUB0ml1ZDSbEMo2S8aVcMrubbI6KfRhnSglW229Ns8hyUytFFRicOnKaK9iTS4j6HkMQbXwSSzXdbakji4LX25NdiQYqyoWBfmkMx03HT2xmZqBKiv7cjGEHhsdycS9Nf56MuOtfjOFheQSAi4D6OZhL+Ag1iQdskEGkWtN4KyZ+Y6yqhH0SMBWTn7LmgY6/Be6tG3tJ5OOHju4WeaTBG5YfynkmgS1X3qsQlunq7klMSsqtN8tyFsffX/0SrTm5BetgwF7nX6W5TOLs2geC4ELbfPRYA7Vn+d30GGAqBB70F7eE/PbI39WgzSbZm2tw2C1buEZ4GyZ9XAVatXxHcU4zZ+7hLnnUIpV0l7bEXBUA2Eje7Vs5W1+FQYziQTullIV7oyGIE5UlVXkEk45QZZ4V4XwtfF2WtbdoHLydr/0KRCoWUUUeMJNa1NdkQyjJV+zC0UnC1FfoZc+mv6tRfl47QOFhCrMbpJ+RJ4G01bBxsJWJP0XTxi6Hf9NV9jnu431odt+fctFap8lAgqRwbhFTlDkf+5NEyXzLCmBXlaxt+ap9Q42mlV7twJU1aOWO20LuCm1pQy41Q8V2WZzy5Onq+bFIE93Po+xBv6CtCRLJJz+4D2FU4mbT4py97fAixw9iW0q/QmlRgNO650lqodQYbH6F7aAoNZBEERTH9AZTMrtO+zyAAEazQ7Y+nmGDmASbXSWoRynwQFpp8U0DmXyRC2lzw0r0HA/2bAqgyfFBCleH2cNmNp6iSwF3kJP+4Yyh6tJFxiWQ41mDs86/YaJhG2uSCQ1bVf/mfJIzwnQVsugQfzCMfmJZn1TmkguQjJOaTLhhdCmf42LdbQdxD4C7+fWoJkZy9U9vBgLKmU8vr4joEkd/8OzI7tZDsYPBaP3aVPujr8jnU55bfu+JS6U+fw5TisD635rXmsLu8N9aHQ4O6rLU+9VTYQ/x2WxnWWZZ+NwElldRpvswCCReyDv2GT5lyZTfjPpIGPjTaIpoJY/mJqg/slr7tn0udDOBRSiJv1V5neyf/p04594WLz2Gk5XB73RavHIl3OdeXCwSH3Yaj+O7VDWVeLtPvOOb/zB/4u9EIajmDTrvOa6QYct83phy396brSRS2mSjLb+dgyH0QBEBpsF4uyiwxNLk4ustKucszg9Be2QF6CvU1x8rW3wMP7VvGvgQPqrOGOxsRrv+Pc4GlisY9B6TorYHTX2JlGbjXtvPFnfZkHFwEuUFFCjO2mpdM4WyB4v/ANHej2rLPJKZf2JOxm2xzeKckDu0z9rfzcfGw5owgeITj1zWHtLU+J3KRVf+Oxwtkbcv+kOCzZo/VMQbxwUf7WE8Cbe+9CaYs+rXFUA3JJ91HkGy0bBYjYXqmb3zeOfpd4oDeghB/h2D6TI9hKLd8yX6ZayDLYPhjXguEDmURId4COtnkQl4WURma9bs45Bf1eTHR61Xxn6ge/Wq1Z+D9RrTBv9Y,iv:z2ZnkkjwqkYRxSSmZ+6YSyF7u3TpJSpx6TInQu451Yo=,tag:JJ90+ruF68nt8XNV7A8+9A==,type:str]
        client-key-data: ENC[AES256_GCM,data:+RuFMzY4OOtxgemogoW4SauKR1tIveAegdpcvtlj3trSa+oJpe5oUFV2If+WQC0AT7zfKaMWFwDimBI7bRi7TGmIKAa5qVykt4Xv0wKf7cLrMtaWcMbY0yperJ1wkCkfW+pyBYmJmwEhS5PbX7baCWj6eT8RJIEWSPFsMsVXnH1RHmTei/1cKLHQxKn93UwIMDt41qZyDr80P1XjwJIpvbMOEsiPVuF2y9I8U1RxfzgSpbhZC+lY0EieMa+0BhOCWbPzmQs3UwpQhVjbohbVrMKQl3nwVLkw877dvO1AtlOXyzuDv0OUZN08+R6LXRz+9/2nrAu6CLVrxvc1CdA08YPZ8jor7XZRDKH4vuOUkazNnKhn4wGxi+nWyV4U2ckxEkLYRaFt9cLJPI3qXIA3JQ==,iv:6Ex5mO7PuWARminhw8beTCZSZvaJtQYmnwM+mY578XM=,tag:9yYB2EEbPPE/V53jJA1hiQ==,type:str]
sops:
    age:
        - recipient: age1ux6jahdtqlrcf3q5n0050vm2sr5qh66m388nfaamct6s643cspdqz8c40f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUStqbGVEVXZvQ1Y5eUxN
            NUZ1UlR0WjEwMTZpZXdLM2NXdVRGSFdiRTBjClk1K0ZpcThTM2VKQ3pDbXdtMVAv
            aVhvR3MwMk5wVDZ2eHdxNUhCeE5qS28KLS0tIHUza3FUVjZmOU1aRXBVL1RxUExy
            eG5LSGZmRjFxSGdrSmdIL09Dc0VadE0Kuz3t6AIu6x0qqaIexrp14ZtL9hs0nEqO
            C75csbxXl+IMDPLn/F801R7WeSqUFaqHyinQSeQnWNMxhsFJaiYS9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age134rsuzlwf7fqzl3zluzjmheez6y4x5mmakfsejpjenr6qy3st3rs3rd5l9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYTNyQjNXZTMyL2Y5OWZR
            OTdnbGp0MFlPYmZYdGdkSlN6TGs2cWo4SzFnClZVNllwYVk2SHhZMThqcjhoeTRE
            UVlPVS9zcSsxaXNsak9KdGhHTFRaNDQKLS0tIGI4Q3cvSVpNNHpUa3ZsczQ0WWJC
            S2VUSmJlNHYxeTZuT3ZtUDlSWnpMU2sKWmbWgcQUs0CpiX+o9DR4eK6n3i78/sPm
            4LlEGnIh/syIN3gDTYpYH8Ats1Mud8nxfADCOuNxKrfkSXjfw/JJ5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sytxxylgnjkdev2qjds6zdwn6ynt73tn4u7lvg27cjdwj97lj4xs75ycyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2L1U3K1FRTkxSNW5TTHdX
            SHV6QVZuL3BrOE1oWEJXY3cxb0dUWVRrWnpBCmkraG9Nc05LdVJPT0ZEK3J0Vmpm
            SlB5a3lwQmdKQ3NDcmcvbE9KeFp6dXMKLS0tIG10ZlhTNXVGcUNWcjJONmVrRHZ3
            WThzU3RZMmpIWkpZWG41YmhsUlhUOFkKh/jZigLyu6ABH5R5hNm1tXazyAdYV2xQ
            W2BAeEauoQrMQI+TDrB2MWCcmhm4CJH3hf4VXd1Dr/V3KIPQ8OjJ4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uwv74ykhvs45aftm8d4v03ry44jdkt93nmslhktc2u4fq7j7yyqg5zdph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5N2h2VnVmZmRWYjZwYVBw
            WHdCQ1BNWnVxZW1BYXlZWkowbm9kdTRkWFZjCjZ6TGNEZEUwUVFtR2VkbHdYREpQ
            SjV6UDc5Y1FSN3kxaEplWkI1ckdMeGsKLS0tIDZ0TGM0VHo5YW5GNUFnOWJhZ2Zn
            c08vNS9nMlhLU3pYZVdEdTFJRE5IbDQKLLm6N89bii7jvYIr/TE0PKCpUMfCmenC
            oZwXFgtxvvfjggVtgAnWUwZMAX01IXFIDCdhENn2qngQ5UT6Sy7Dhw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y8n63p4zrlzxphe9k7hlc27vhk3g3k32nz0p4eg66tz4p2pnjavq4aq3xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaLzlqS3hFSWk1N042RFNi
            ZzByclp3emR0UjBLaDJjdEtiYzAxRXIzMVRnCnBrdFI0MXgrNW9TaUZ6Yit0N3U3
            aUx5WTF3UlE0cERjSHdQVHRkTXhGNU0KLS0tIGtpMVNuN2l6VE1NVmRxMlJ5YUE2
            dmJuVnA0THFucEZPWGMzOXN1UEV4b0kKNKwqlZrwsuag5GHVR9/fjUflOoxRVN//
            SbnCNmeLKyzThfY7Kyzwr8Zv61i6Qha7cMAeikrc2DTr026gQ829hA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T00:57:37Z"
    mac: ENC[AES256_GCM,data:ttf1Xhwu5/TDhoYxeAqArj4cBx9VPHO8cme2xHArIJzjvtTOX9wj4ZUuXD1JTtHu88LrPUB3etVL9P91GuE/dp5TWSXsKW7DaLXRDYZxRJa4Xxv5d7JAJXoDFR/WtrMH1TehkkwZWOOoGN7GTZcWhVmp77ZIRRAGu8c0LCaFAs4=,iv:Q+BG11yzSmSIWEJfzOBdSFSLLiUt+1UgDQXljRlXRe4=,tag:RTaUPjVKUduHtIoPNxxOcg==,type:str]
    pgp:
        - created_at: "2025-10-27T21:40:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DAAAAAAAAAAASAQdAV7pJRQM6jt3WUr5SA0hRw3kI3sVG+GG31fMh7f+nchsw
            zuoFDivSKFJbA0sGrTRthtTOF5Ms2DH07gjJjcVq+wZmbcT7h8KnrINHMEpJ1cyI
            0l4B4xaaWq08UFzxYXhBQayXL++y6Xk9DcC0UUtAKXhZYG32ytguSq36w/0Fmrvh
            Ec6gByYQugyQpR/KTyh4sMJ+CMTTcokjptxcjEnvYZw9SODZNsKhehnWSfI+VtS2
            =LGA/
            -----END PGP MESSAGE-----
          fp: FD5B1635F2218760E010601F4A6E1024D7BBE968
    unencrypted_suffix: _unencrypted
    version: 3.11.0
