apiVersion: v2
name: kube-prometheus-stack
version: 0.1.2
dependencies:
  - name: kube-prometheus-stack
    version: 82.4.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki
    version: 6.53.0
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: promtail
    version: 6.17.1
    repository: https://grafana.github.io/helm-charts
    condition: promtail.enabled
