apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: anubis-ingress-status-patch
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses/status"]
    verbs: ["patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: anubis-ingress-status-patch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anubis-ingress-status-patch
subjects:
  - kind: ServiceAccount
    name: anubis-ingress-anubis
    namespace: anubis
