apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foundation-root
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: "http://gitea-http.gitea:3000/ops/k8s-homelab"
    targetRevision: "main"
    path: "k8s/foundation"
    directory:
      include: "**/application.yaml"
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    # When prune / selfHeal are explicitly set to false, the application gets stuck in an OutOfSync loop.
    # This is because the values have the `omitempty` json tag, which means after applying the changes,
    # automated will be an empty object.
    # See https://github.com/argoproj/argo-cd/issues/22546
    automated: {}
    #   prune: false
    #   selfHeal: false
