apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: "{{ .Release.Namespace }}"
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: "Cluster management"
    gethomepage.dev/name: "ArgoCD"
    gethomepage.dev/description: "Continuous delivery"
    gethomepage.dev/icon: "argocd.svg"
    gethomepage.dev/href: "https://argocd.msng.to"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=argo-cd-server"
    gethomepage.dev/widget.type: "argocd"
    gethomepage.dev/widget.url: "https://argocd.msng.to"
    gethomepage.dev/widget.key: {{ "{{HOMEPAGE_VAR_ARGOCD_API_KEY}}" | quote }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.msng.to`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.msng.to`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
