apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  settings.yaml: |-
    title: "Missingtoken's Homelab"
    description: "Missingtoken's Homelab"
    favicon: https://missingtoken.net/favicon.ico
    theme: dark
    hideVersion: true
    disableUpdateCheck: true
    # use a green dot for healthy status
    statusStyle: "dot"
    providers:
      longhorn:
        url: https://longhorn.msng.to
  kubernetes.yaml: |-
    mode: cluster
    ingress: true
    traefik: true
    gateway: true
  services.yaml: |-
    []
  bookmarks.yaml: |-
    []
  widgets.yaml: |-
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        label: nas
        disk: /mnt/nas
        expanded: true
    - longhorn:
        expanded: true
        total: true
