apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
    - public
  nodeSelectors:
    - matchLabels:
        node-role.kubernetes.io/control-plane: "true"
