apiVersion: v1
kind: Service
metadata:
  name: traefik-public
  namespace: kube-system
  annotations:
    metallb.universe.tf/address-pool: public
spec:
  type: LoadBalancer
  loadBalancerClass: metallb
  loadBalancerIP: 10.69.80.120
  externalTrafficPolicy: Local
  ports:
    - name: webpublic
      port: 80
      protocol: TCP
      targetPort: webpublic
    - name: websecurepublic
      port: 443
      protocol: TCP
      targetPort: websecurepublic
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
