---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.crowdsec.secrets.externalSecret.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: {{ .Values.crowdsec.secrets.externalSecret.csLapiSecretKey }},{{ .Values.crowdsec.secrets.externalSecret.registrationTokenKey }}
    secret-generator.v1.mittwald.de/length: "64"
    secret-generator.v1.mittwald.de/encoding: base64
type: Opaque
data:
