# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: crowdsec-psql
  namespace: {{ .Release.Namespace }}
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5-standard-bookworm
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    # Use single replica storageclass to avoid write amplification with multiple instances.
    storageClass: longhorn-rc1
  enableSuperuserAccess: true
  postgresql:
    # postgresql configuration options (postgresql.conf)
    parameters:
      # CrowdSec has relatively low connection needs
      max_connections: "100"
      shared_buffers: 128MB
      # Reduce checkpoint frequency to lower I/O spikes (default 5min)
      checkpoint_timeout: 15min
      # Increase WAL size to allow less frequent checkpoints
      max_wal_size: 1GB
  monitoring:
    enablePodMonitor: true
  # Disable pod disruption budget so that the cluster can be shut down
  enablePDB: false
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi
  bootstrap:
    initdb:
      database: crowdsec
      owner: crowdsec
