{{- if .Values.authelia.secret -}}
  {{- if .Values.authelia.secret.existingSecret -}}
    {{- if ne "" .Values.authelia.secret.existingSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.authelia.secret.existingSecret}}
  namespace: {{ .Release.Namespace }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: identity_validation.reset_password.jwt.hmac.key,session.encryption.key,session.redis.password.txt,session.redis.sentinel.password.txt,storage.encryption.key,identity_providers.oidc.hmac.key
    secret-generator.v1.mittwald.de/length: "128"
data: {}
    {{- end -}}
  {{- end -}}
{{- end -}}
