---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authelia-tls-certificate
  namespace: {{ .Release.Namespace }}
spec:
  # The secret name to store the signed certificate
  secretName: {{ .Values.authelia.ingress.tls.secret }}
  # DNS SAN
  dnsNames: [
    authelia.msng.to
  ]
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
