apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-system
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: monitoring-system
  ignoreDifferences:
    # These secrets use generated values
    - kind: Secret
      namespace: monitoring-system
      name: hubble-server-certs
      jsonPointers:
        - /data
    - kind: Secret
      namespace: monitoring-system
      name: alertmanager-monitoring-system-kube-pro
      jsonPointers:
        - /data
    # Prometheus CRDs are managed by a helm hook and can be ignored by Argo
    - kind: CustomResourceDefinition
      group: apiextensions.k8s.io
  project: default
  source:
    path: platform/monitoring-system
    repoURL: http://gitea-http.gitea:3000/ops/k8s-homelab
    targetRevision: main
